all: plot

plot:
	python3 main.py --scenario=plot_metric --metric=peak_aoi
	python3 main.py --scenario=plot_metric --metric=n_packet
	python3 main.py --scenario=legend_metric
# 	python3 main.py --scenario=plot_metric --metric=action
# 	python3 main.py --scenario=plot_metric --metric=n_wait
# 	python3 main.py --scenario=plot_metric --metric=delay
